
version: '3.8'

services:
  backend_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: static
        target: /static
      - type: bind
        source: .
        target: /app
    # env_file:
    #   - .env
    ports:
      - "8000:8000"
    networks:
      - main
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 3s
      timeout: 3s
      retries: 3
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:16-alpine
    environment:
      # - POSTGRES_DB=${DATABASE_NAME}
      # - POSTGRES_USER=${DATABASE_USERNAME}
      # - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54321:5432"
    restart: always
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5





volumes:
  app:
  static:
  postgres_data:


networks:
  main:
